SUPABASE_URL = "https://ppksdqjfbfrwndfasstw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwa3NkcWpmYmZyd25kZmFzc3R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzY5NTgsImV4cCI6MjA3MTMxMjk1OH0.QaBDmCLaQD28rBmOMqoGtTMY2v8ZPVDNStZ10JBCqQE"
